name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - master  # Change this to 'main' if that's your default branch

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI/CD
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/69982305/trigger/pipeline \
            -F token=$GITLAB_TRIGGER_TOKEN \
            -F ref=main
        env:
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
